FROM python:3.13-slim

LABEL maintainer="Renix"
LABEL description="FritzDect2MQTT Docker Container"

RUN apt-get update && apt-get install -y \
    git \
    vim \
    nano \
    supervisor \
    iputils-ping \
    logrotate && \
    apt-get clean

# Arbeitsverzeichnis
WORKDIR /fritzdect2mqtt
COPY . /fritzdect2mqtt

# Optional: Repository klonen (alternativ vor dem Build manuell tun)
# RUN git clone --branch moonraker-fritz https://github.com/SirRenix/FritzDect2MQTT.git .

# Kopiere lokale Konfigs in den Container
COPY docker/supervisor/supervisord.conf /etc/supervisord.conf
COPY docker/supervisor/fritzdect2mqtt.conf /etc/supervisor/conf.d/fritzdect2mqtt.conf

# Abhängigkeiten installieren
RUN pip install --no-cache-dir -r requirements.txt

# Logrotate config
COPY docker/logrotate/fritzdect2mqttdocker.logrotate /etc/logrotate.d/fritzdect2mqttdocker

# Logs sollen nicht unendlich wachsen
ENV PYTHONUNBUFFERED=1

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
