# Verwende Python 3.13 als Basis-Image
FROM python:3.13-slim

# Setze das Image-Label für bessere Identifikation
LABEL maintainer="SirRenix"
LABEL version="1.0"
LABEL description="FritzDect2MQTT - MQTT Schnittstelle für Fritz!Dect"

# Installiere benötigte Systempakete (ohne SSH)
RUN apt-get update && apt-get install -y \
    git \
    vim \
    nano \
    supervisor \
    iputils-ping \
    logrotate && \
    apt-get clean

# Setze das Arbeitsverzeichnis auf Root, damit Git das Verzeichnis anlegt
WORKDIR /

# Klone das Repository direkt nach /fritzdect2mqtt
RUN git clone --single-branch --branch moonraker-fritz https://github.com/SirRenix/FritzDect2MQTT.git /fritzdect2mqtt

# Kopiere die aktualisierte Supervisor- und Logrotate-Konfiguration aus dem Docker-Ordner
COPY /fritzdect2mqtt/docker/supervisord.conf /fritzdect2mqtt/supervisord.conf
COPY /fritzdect2mqtt/docker/fritzdect2MQTTdocker.logrotate /etc/logrotate.d/fritzdect2MQTTdocker

# Kopiere requirements.txt und installiere Python-Abhängigkeiten
COPY requirements.txt /fritzdect2mqtt/requirements.txt
RUN pip install --no-cache-dir -r /fritzdect2mqtt/requirements.txt

# Standardmäßiger Startbefehl: Supervisor
CMD ["/bin/sh", "-c", "exec /usr/bin/supervisord -n -c /fritzdect2mqtt/supervisord.conf"]
