version: '3.8'

services:
  FritzDect2MQTT:
    build: 
        context: ..
        dockerfile: docker/Dockerfile
    image: fritzdect2mqtt:dockerqnap
    container_name: FritzDect2MQTT
    restart: unless-stopped  # startet bei Fehlern oder Reboot automatisch neu
    volumes:
      - /share/Container/FritzDect2MQTT:/fritzdect2mqtt
      - /share/Container/FritzDect2MQTT/logs:/fritzdect2mqtt/logs
      - /share/Container/FritzDect2MQTT/config:/fritzdect2mqtt/config
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /fritzdect2mqtt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "FritzDect2MQTT.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
