[program:fritzdectmqtt]
command=python3 /fritzdect2mqtt/FritzDect2MQTT.py
directory=/fritzdect2mqtt
autostart=true
autorestart=true
startretries=5
stdout_logfile=/fritzdect2mqtt/logs/fritzdectmqtt.out.log
stderr_logfile=/fritzdect2mqtt/logs/fritzdectmqtt.err.log
